# Generated by Django 5.0.4 on 2024-06-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='product_title_9e36ed_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
